using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ChinaWJ
{
    public class Citys
    {
        public List<List<string>> citys()
        {
            List<List<string>> citys = new List<List<string>>();
            citys.Add(new List<string>() { "41", "上海市", "1" });
            citys.Add(new List<string>() { "52", "临沧市", "2" });
            citys.Add(new List<string>() { "361", "西双版纳州", "2" });
            citys.Add(new List<string>() { "333", "红河州", "2" });
            citys.Add(new List<string>() { "308", "玉溪市", "2" });
            citys.Add(new List<string>() { "251", "楚雄州", "2" });
            citys.Add(new List<string>() { "234", "曲靖市", "2" });
            citys.Add(new List<string>() { "232", "普洱市", "2" });
            citys.Add(new List<string>() { "229", "昭通市", "2" });
            citys.Add(new List<string>() { "225", "昆明市", "2" });
            citys.Add(new List<string>() { "216", "文山州", "2" });
            citys.Add(new List<string>() { "205", "怒江州", "2" });
            citys.Add(new List<string>() { "199", "德宏州", "2" });
            citys.Add(new List<string>() { "142", "大理州", "2" });
            citys.Add(new List<string>() { "76", "保山市", "2" });
            citys.Add(new List<string>() { "56", "丽江市", "2" });
            citys.Add(new List<string>() { "376", "迪庆州", "2" });
            citys.Add(new List<string>() { "57", "乌兰察布市", "3" });
            citys.Add(new List<string>() { "401", "锡林郭勒盟", "3" });
            citys.Add(new List<string>() { "387", "鄂尔多斯市", "3" });
            citys.Add(new List<string>() { "378", "通辽市", "3" });
            citys.Add(new List<string>() { "370", "赤峰市", "3" });
            citys.Add(new List<string>() { "178", "巴彦淖尔市", "3" });
            citys.Add(new List<string>() { "118", "呼和浩特市", "3" });
            citys.Add(new List<string>() { "117", "呼伦贝尔市", "3" });
            citys.Add(new List<string>() { "87", "包头市", "3" });
            citys.Add(new List<string>() { "84", "兴安盟", "3" });
            citys.Add(new List<string>() { "58", "乌海市", "3" });
            citys.Add(new List<string>() { "415", "阿拉善盟", "3" });
            citys.Add(new List<string>() { "88", "北京市", "4" });
            citys.Add(new List<string>() { "63", "云林县", "5" });
            citys.Add(new List<string>() { "169", "屏东县", "5" });
            citys.Add(new List<string>() { "197", "彰化县", "5" });
            citys.Add(new List<string>() { "220", "新竹县", "5" });
            citys.Add(new List<string>() { "221", "新竹市", "5" });
            citys.Add(new List<string>() { "247", "桃园县", "5" });
            citys.Add(new List<string>() { "301", "澎湖县", "5" });
            citys.Add(new List<string>() { "342", "花莲县", "5" });
            citys.Add(new List<string>() { "344", "苗栗县", "5" });
            citys.Add(new List<string>() { "428", "高雄县", "5" });
            citys.Add(new List<string>() { "161", "宜兰县", "5" });
            citys.Add(new List<string>() { "137", "基隆市", "5" });
            citys.Add(new List<string>() { "129", "嘉义市", "5" });
            citys.Add(new List<string>() { "95", "南投县", "5" });
            citys.Add(new List<string>() { "102", "台东县", "5" });
            citys.Add(new List<string>() { "103", "台中县", "5" });
            citys.Add(new List<string>() { "104", "台中市", "5" });
            citys.Add(new List<string>() { "105", "台北县", "5" });
            citys.Add(new List<string>() { "106", "台北市", "5" });
            citys.Add(new List<string>() { "107", "台南县", "5" });
            citys.Add(new List<string>() { "108", "台南市", "5" });
            citys.Add(new List<string>() { "128", "嘉义县", "5" });
            citys.Add(new List<string>() { "429", "高雄市", "5" });
            citys.Add(new List<string>() { "112", "吉林市", "6" });
            citys.Add(new List<string>() { "132", "四平市", "6" });
            citys.Add(new List<string>() { "190", "延边朝鲜族自治州", "6" });
            citys.Add(new List<string>() { "240", "松原市", "6" });
            citys.Add(new List<string>() { "315", "白城市", "6" });
            citys.Add(new List<string>() { "316", "白山市", "6" });
            citys.Add(new List<string>() { "371", "辽源市", "6" });
            citys.Add(new List<string>() { "377", "通化市", "6" });
            citys.Add(new List<string>() { "404", "长春市", "6" });
            citys.Add(new List<string>() { "61", "乐山市", "7" });
            citys.Add(new List<string>() { "314", "甘孜州", "7" });
            citys.Add(new List<string>() { "323", "眉山市", "7" });
            citys.Add(new List<string>() { "336", "绵阳市", "7" });
            citys.Add(new List<string>() { "339", "自贡市", "7" });
            citys.Add(new List<string>() { "368", "资阳市", "7" });
            citys.Add(new List<string>() { "373", "达州市", "7" });
            citys.Add(new List<string>() { "379", "遂宁市", "7" });
            citys.Add(new List<string>() { "414", "阿坝州", "7" });
            citys.Add(new List<string>() { "270", "泸州市", "7" });
            citys.Add(new List<string>() { "215", "攀枝花市", "7" });
            citys.Add(new List<string>() { "208", "成都市", "7" });
            citys.Add(new List<string>() { "85", "内江市", "7" });
            citys.Add(new List<string>() { "86", "凉山州", "7" });
            citys.Add(new List<string>() { "92", "南充市", "7" });
            citys.Add(new List<string>() { "162", "宜宾市", "7" });
            citys.Add(new List<string>() { "177", "巴中市", "7" });
            citys.Add(new List<string>() { "184", "广元市", "7" });
            citys.Add(new List<string>() { "185", "广安市", "7" });
            citys.Add(new List<string>() { "201", "德阳市", "7" });
            citys.Add(new List<string>() { "421", "雅安市", "7" });
            citys.Add(new List<string>() { "146", "天津市", "8" });
            citys.Add(new List<string>() { "46", "中卫市", "9" });
            citys.Add(new List<string>() { "115", "吴忠市", "9" });
            citys.Add(new List<string>() { "133", "固原市", "9" });
            citys.Add(new List<string>() { "324", "石嘴山市", "9" });
            citys.Add(new List<string>() { "400", "银川市", "9" });
            citys.Add(new List<string>() { "68", "亳州市", "10" });
            citys.Add(new List<string>() { "426", "马鞍山市", "10" });
            citys.Add(new List<string>() { "408", "阜阳市", "10" });
            citys.Add(new List<string>() { "399", "铜陵市", "10" });
            citys.Add(new List<string>() { "355", "蚌埠市", "10" });
            citys.Add(new List<string>() { "341", "芜湖市", "10" });
            citys.Add(new List<string>() { "292", "滁州市", "10" });
            citys.Add(new List<string>() { "282", "淮南市", "10" });
            citys.Add(new List<string>() { "281", "淮北市", "10" });
            citys.Add(new List<string>() { "262", "池州市", "10" });
            citys.Add(new List<string>() { "174", "巢湖市", "10" });
            citys.Add(new List<string>() { "167", "宿州市", "10" });
            citys.Add(new List<string>() { "166", "宣城市", "10" });
            citys.Add(new List<string>() { "155", "安庆市", "10" });
            citys.Add(new List<string>() { "110", "合肥市", "10" });
            citys.Add(new List<string>() { "81", "六安市", "10" });
            citys.Add(new List<string>() { "436", "黄山市", "10" });
            citys.Add(new List<string>() { "45", "东营市", "11" });
            citys.Add(new List<string>() { "351", "菏泽市", "11" });
            citys.Add(new List<string>() { "350", "莱芜市", "11" });
            citys.Add(new List<string>() { "337", "聊城市", "11" });
            citys.Add(new List<string>() { "303", "烟台市", "11" });
            citys.Add(new List<string>() { "296", "潍坊市", "11" });
            citys.Add(new List<string>() { "293", "滨州市", "11" });
            citys.Add(new List<string>() { "280", "淄博市", "11" });
            citys.Add(new List<string>() { "273", "济宁市", "11" });
            citys.Add(new List<string>() { "272", "济南市", "11" });
            citys.Add(new List<string>() { "268", "泰安市", "11" });
            citys.Add(new List<string>() { "243", "枣庄市", "11" });
            citys.Add(new List<string>() { "224", "日照市", "11" });
            citys.Add(new List<string>() { "200", "德州市", "11" });
            citys.Add(new List<string>() { "150", "威海市", "11" });
            citys.Add(new List<string>() { "51", "临沂市", "11" });
            citys.Add(new List<string>() { "422", "青岛市", "11" });
            citys.Add(new List<string>() { "50", "临汾市", "12" });
            citys.Add(new List<string>() { "406", "长治市", "12" });
            citys.Add(new List<string>() { "374", "运城市", "12" });
            citys.Add(new List<string>() { "235", "朔州市", "12" });
            citys.Add(new List<string>() { "231", "晋城市", "12" });
            citys.Add(new List<string>() { "230", "晋中市", "12" });
            citys.Add(new List<string>() { "203", "忻州市", "12" });
            citys.Add(new List<string>() { "148", "太原市", "12" });
            citys.Add(new List<string>() { "140", "大同市", "12" });
            citys.Add(new List<string>() { "114", "吕梁市", "12" });
            citys.Add(new List<string>() { "411", "阳泉市", "12" });
            citys.Add(new List<string>() { "44", "东莞市", "13" });
            citys.Add(new List<string>() { "284", "深圳市", "13" });
            citys.Add(new List<string>() { "285", "清远市", "13" });
            citys.Add(new List<string>() { "291", "湛江市", "13" });
            citys.Add(new List<string>() { "298", "潮州市", "13" });
            citys.Add(new List<string>() { "309", "珠海市", "13" });
            citys.Add(new List<string>() { "338", "肇庆市", "13" });
            citys.Add(new List<string>() { "345", "茂名市", "13" });
            citys.Add(new List<string>() { "410", "阳江市", "13" });
            citys.Add(new List<string>() { "266", "河源市", "13" });
            citys.Add(new List<string>() { "261", "江门市", "13" });
            citys.Add(new List<string>() { "260", "汕尾市", "13" });
            citys.Add(new List<string>() { "47", "中山市", "13" });
            citys.Add(new List<string>() { "64", "云浮市", "13" });
            citys.Add(new List<string>() { "72", "佛山市", "13" });
            citys.Add(new List<string>() { "186", "广州市", "13" });
            citys.Add(new List<string>() { "207", "惠州市", "13" });
            citys.Add(new List<string>() { "214", "揭阳市", "13" });
            citys.Add(new List<string>() { "249", "梅州市", "13" });
            citys.Add(new List<string>() { "259", "汕头市", "13" });
            citys.Add(new List<string>() { "424", "韶关市", "13" });
            citys.Add(new List<string>() { "89", "北海市", "14" });
            citys.Add(new List<string>() { "394", "钦州市", "14" });
            citys.Add(new List<string>() { "367", "贺州市", "14" });
            citys.Add(new List<string>() { "365", "贵港市", "14" });
            citys.Add(new List<string>() { "319", "百色市", "14" });
            citys.Add(new List<string>() { "306", "玉林市", "14" });
            citys.Add(new List<string>() { "265", "河池市", "14" });
            citys.Add(new List<string>() { "250", "梧州市", "14" });
            citys.Add(new List<string>() { "246", "桂林市", "14" });
            citys.Add(new List<string>() { "244", "柳州市", "14" });
            citys.Add(new List<string>() { "238", "来宾市", "14" });
            citys.Add(new List<string>() { "173", "崇左市", "14" });
            citys.Add(new List<string>() { "93", "南宁市", "14" });
            citys.Add(new List<string>() { "409", "防城港市", "14" });
            citys.Add(new List<string>() { "59", "乌鲁木齐市", "15" });
            citys.Add(new List<string>() { "413", "阿勒泰地区", "15" });
            citys.Add(new List<string>() { "412", "阿克苏地区", "15" });
            citys.Add(new List<string>() { "327", "石河子市", "15" });
            citys.Add(new List<string>() { "226", "昌吉回族自治州", "15" });
            citys.Add(new List<string>() { "179", "巴音郭楞蒙古自治州", "15" });
            citys.Add(new List<string>() { "138", "塔城地区", "15" });
            citys.Add(new List<string>() { "134", "图木舒克市", "15" });
            citys.Add(new List<string>() { "127", "喀什地区", "15" });
            citys.Add(new List<string>() { "122", "哈密地区", "15" });
            citys.Add(new List<string>() { "119", "和田地区", "15" });
            citys.Add(new List<string>() { "113", "吐鲁番地区", "15" });
            citys.Add(new List<string>() { "99", "博尔塔拉蒙古自治州", "15" });
            citys.Add(new List<string>() { "80", "克拉玛依市", "15" });
            citys.Add(new List<string>() { "79", "克孜勒苏柯尔克孜自治州", "15" });
            citys.Add(new List<string>() { "71", "伊犁哈萨克自治州", "15" });
            citys.Add(new List<string>() { "66", "五家渠市", "15" });
            citys.Add(new List<string>() { "416", "阿拉尔市", "15" });
            citys.Add(new List<string>() { "91", "南京市", "16" });
            citys.Add(new List<string>() { "375", "连云港市", "16" });
            citys.Add(new List<string>() { "343", "苏州市", "16" });
            citys.Add(new List<string>() { "321", "盐城市", "16" });
            citys.Add(new List<string>() { "283", "淮安市", "16" });
            citys.Add(new List<string>() { "269", "泰州市", "16" });
            citys.Add(new List<string>() { "222", "无锡市", "16" });
            citys.Add(new List<string>() { "209", "扬州市", "16" });
            citys.Add(new List<string>() { "198", "徐州市", "16" });
            citys.Add(new List<string>() { "180", "常州市", "16" });
            citys.Add(new List<string>() { "168", "宿迁市", "16" });
            citys.Add(new List<string>() { "97", "南通市", "16" });
            citys.Add(new List<string>() { "403", "镇江市", "16" });
            citys.Add(new List<string>() { "42", "上饶市", "17" });
            citys.Add(new List<string>() { "369", "赣州市", "17" });
            citys.Add(new List<string>() { "352", "萍乡市", "17" });
            citys.Add(new List<string>() { "233", "景德镇市", "17" });
            citys.Add(new List<string>() { "219", "新余市", "17" });
            citys.Add(new List<string>() { "211", "抚州市", "17" });
            citys.Add(new List<string>() { "164", "宜春市", "17" });
            citys.Add(new List<string>() { "111", "吉安市", "17" });
            citys.Add(new List<string>() { "96", "南昌市", "17" });
            citys.Add(new List<string>() { "62", "九江市", "17" });
            citys.Add(new List<string>() { "433", "鹰潭市", "17" });
            citys.Add(new List<string>() { "75", "保定市", "18" });
            citys.Add(new List<string>() { "381", "邢台市", "18" });
            citys.Add(new List<string>() { "356", "衡水市", "18" });
            citys.Add(new List<string>() { "331", "秦皇岛市", "18" });
            citys.Add(new List<string>() { "325", "石家庄市", "18" });
            citys.Add(new List<string>() { "264", "沧州市", "18" });
            citys.Add(new List<string>() { "210", "承德市", "18" });
            citys.Add(new List<string>() { "193", "张家口市", "18" });
            citys.Add(new List<string>() { "188", "廊坊市", "18" });
            citys.Add(new List<string>() { "124", "唐山市", "18" });
            citys.Add(new List<string>() { "383", "邯郸市", "18" });
            citys.Add(new List<string>() { "40", "三门峡市", "19" });
            citys.Add(new List<string>() { "427", "驻马店市", "19" });
            citys.Add(new List<string>() { "385", "郑州市", "19" });
            citys.Add(new List<string>() { "364", "许昌市", "19" });
            citys.Add(new List<string>() { "304", "焦作市", "19" });
            citys.Add(new List<string>() { "302", "濮阳市", "19" });
            citys.Add(new List<string>() { "294", "漯河市", "19" });
            citys.Add(new List<string>() { "274", "济源市", "19" });
            citys.Add(new List<string>() { "271", "洛阳市", "19" });
            citys.Add(new List<string>() { "218", "新乡市", "19" });
            citys.Add(new List<string>() { "192", "开封市", "19" });
            citys.Add(new List<string>() { "183", "平顶山市", "19" });
            citys.Add(new List<string>() { "157", "安阳市", "19" });
            citys.Add(new List<string>() { "125", "商丘市", "19" });
            citys.Add(new List<string>() { "116", "周口市", "19" });
            citys.Add(new List<string>() { "98", "南阳市", "19" });
            citys.Add(new List<string>() { "77", "信阳市", "19" });
            citys.Add(new List<string>() { "431", "鹤壁市", "19" });
            citys.Add(new List<string>() { "55", "丽水市", "20" });
            citys.Add(new List<string>() { "358", "衢州市", "20" });
            citys.Add(new List<string>() { "340", "舟山市", "20" });
            citys.Add(new List<string>() { "334", "绍兴市", "20" });
            citys.Add(new List<string>() { "288", "湖州市", "20" });
            citys.Add(new List<string>() { "286", "温州市", "20" });
            citys.Add(new List<string>() { "239", "杭州市", "20" });
            citys.Add(new List<string>() { "154", "宁波市", "20" });
            citys.Add(new List<string>() { "130", "嘉兴市", "20" });
            citys.Add(new List<string>() { "109", "台州市", "20" });
            citys.Add(new List<string>() { "392", "金华市", "20" });
            citys.Add(new List<string>() { "37", "万宁市", "21" });
            citys.Add(new List<string>() { "360", "西南中沙群岛办事处", "21" });
            citys.Add(new List<string>() { "317", "白沙黎族自治县", "21" });
            citys.Add(new List<string>() { "311", "琼海市", "21" });
            citys.Add(new List<string>() { "310", "琼中黎族苗族自治县", "21" });
            citys.Add(new List<string>() { "300", "澄迈县", "21" });
            citys.Add(new List<string>() { "278", "海口市", "21" });
            citys.Add(new List<string>() { "227", "昌江黎族自治县", "21" });
            citys.Add(new List<string>() { "217", "文昌市", "21" });
            citys.Add(new List<string>() { "170", "屯昌县", "21" });
            citys.Add(new List<string>() { "159", "定安县", "21" });
            citys.Add(new List<string>() { "78", "儋州市", "21" });
            citys.Add(new List<string>() { "74", "保亭黎族苗族自治县", "21" });
            citys.Add(new List<string>() { "67", "五指山市", "21" });
            citys.Add(new List<string>() { "60", "乐东黎族自治县", "21" });
            citys.Add(new List<string>() { "53", "临高县", "21" });
            citys.Add(new List<string>() { "43", "东方市", "21" });
            citys.Add(new List<string>() { "38", "三亚市", "21" });
            citys.Add(new List<string>() { "419", "陵水黎族自治县", "21" });
            citys.Add(new List<string>() { "69", "仙桃市", "22" });
            citys.Add(new List<string>() { "434", "黄冈市", "22" });
            citys.Add(new List<string>() { "420", "随州市", "22" });
            citys.Add(new List<string>() { "388", "鄂州市", "22" });
            citys.Add(new List<string>() { "359", "襄樊市", "22" });
            citys.Add(new List<string>() { "347", "荆门市", "22" });
            citys.Add(new List<string>() { "346", "荆州市", "22" });
            citys.Add(new List<string>() { "328", "神农架林区", "22" });
            citys.Add(new List<string>() { "297", "潜江市", "22" });
            citys.Add(new List<string>() { "254", "武汉市", "22" });
            citys.Add(new List<string>() { "206", "恩施州", "22" });
            citys.Add(new List<string>() { "163", "宜昌市", "22" });
            citys.Add(new List<string>() { "152", "孝感市", "22" });
            citys.Add(new List<string>() { "147", "天门市", "22" });
            citys.Add(new List<string>() { "120", "咸宁市", "22" });
            citys.Add(new List<string>() { "90", "十堰市", "22" });
            citys.Add(new List<string>() { "437", "黄石市", "22" });
            citys.Add(new List<string>() { "151", "娄底市", "23" });
            citys.Add(new List<string>() { "386", "郴州市", "23" });
            citys.Add(new List<string>() { "384", "邵阳市", "23" });
            citys.Add(new List<string>() { "357", "衡阳市", "23" });
            citys.Add(new List<string>() { "320", "益阳市", "23" });
            citys.Add(new List<string>() { "290", "湘西州", "23" });
            citys.Add(new List<string>() { "289", "湘潭市", "23" });
            citys.Add(new List<string>() { "257", "永州市", "23" });
            citys.Add(new List<string>() { "245", "株洲市", "23" });
            citys.Add(new List<string>() { "204", "怀化市", "23" });
            citys.Add(new List<string>() { "194", "张家界市", "23" });
            citys.Add(new List<string>() { "181", "常德市", "23" });
            citys.Add(new List<string>() { "172", "岳阳市", "23" });
            citys.Add(new List<string>() { "405", "长沙市", "23" });
            citys.Add(new List<string>() { "49", "临夏州", "25" });
            citys.Add(new List<string>() { "393", "金昌市", "25" });
            citys.Add(new List<string>() { "390", "酒泉市", "25" });
            citys.Add(new List<string>() { "318", "白银市", "25" });
            citys.Add(new List<string>() { "313", "甘南州", "25" });
            citys.Add(new List<string>() { "253", "武威市", "25" });
            citys.Add(new List<string>() { "195", "张掖市", "25" });
            citys.Add(new List<string>() { "187", "庆阳市", "25" });
            citys.Add(new List<string>() { "182", "平凉市", "25" });
            citys.Add(new List<string>() { "160", "定西市", "25" });
            citys.Add(new List<string>() { "145", "天水市", "25" });
            citys.Add(new List<string>() { "131", "嘉峪关市", "25" });
            citys.Add(new List<string>() { "83", "兰州市", "25" });
            citys.Add(new List<string>() { "418", "陇南市", "25" });
            citys.Add(new List<string>() { "39", "三明市", "26" });
            citys.Add(new List<string>() { "94", "南平市", "26" });
            citys.Add(new List<string>() { "100", "厦门市", "26" });
            citys.Add(new List<string>() { "153", "宁德市", "26" });
            citys.Add(new List<string>() { "267", "泉州市", "26" });
            citys.Add(new List<string>() { "295", "漳州市", "26" });
            citys.Add(new List<string>() { "329", "福州市", "26" });
            citys.Add(new List<string>() { "349", "莆田市", "26" });
            citys.Add(new List<string>() { "443", "龙岩市", "26" });
            citys.Add(new List<string>() { "171", "山南地区", "27" });
            citys.Add(new List<string>() { "213", "拉萨市", "27" });
            citys.Add(new List<string>() { "223", "日喀则地区", "27" });
            citys.Add(new List<string>() { "228", "昌都地区", "27" });
            citys.Add(new List<string>() { "241", "林芝地区", "27" });
            citys.Add(new List<string>() { "382", "那曲地区", "27" });
            citys.Add(new List<string>() { "417", "阿里地区", "27" });
            citys.Add(new List<string>() { "82", "六盘水市", "28" });
            citys.Add(new List<string>() { "158", "安顺市", "28" });
            citys.Add(new List<string>() { "256", "毕节地区", "28" });
            citys.Add(new List<string>() { "366", "贵阳市", "28" });
            citys.Add(new List<string>() { "380", "遵义市", "28" });
            citys.Add(new List<string>() { "396", "铜仁地区", "28" });
            citys.Add(new List<string>() { "439", "黔东南州", "28" });
            citys.Add(new List<string>() { "440", "黔南州", "28" });
            citys.Add(new List<string>() { "441", "黔西南州", "28" });
            citys.Add(new List<string>() { "54", "丹东市", "29" });
            citys.Add(new List<string>() { "407", "阜新市", "29" });
            citys.Add(new List<string>() { "402", "锦州市", "29" });
            citys.Add(new List<string>() { "395", "铁岭市", "29" });
            citys.Add(new List<string>() { "372", "辽阳市", "29" });
            citys.Add(new List<string>() { "354", "葫芦岛市", "29" });
            citys.Add(new List<string>() { "353", "营口市", "29" });
            citys.Add(new List<string>() { "322", "盘锦市", "29" });
            citys.Add(new List<string>() { "263", "沈阳市", "29" });
            citys.Add(new List<string>() { "237", "本溪市", "29" });
            citys.Add(new List<string>() { "236", "朝阳市", "29" });
            citys.Add(new List<string>() { "212", "抚顺市", "29" });
            citys.Add(new List<string>() { "144", "大连市", "29" });
            citys.Add(new List<string>() { "423", "鞍山市", "29" });
            citys.Add(new List<string>() { "48", "丰都县", "30" });
            citys.Add(new List<string>() { "299", "潼南县", "30" });
            citys.Add(new List<string>() { "312", "璧山县", "30" });
            citys.Add(new List<string>() { "326", "石柱土家族自治县", "30" });
            citys.Add(new List<string>() { "330", "秀山土家族苗族自治县", "30" });
            citys.Add(new List<string>() { "332", "綦江县", "30" });
            citys.Add(new List<string>() { "348", "荣昌县", "30" });
            citys.Add(new List<string>() { "389", "酉阳土家族苗族自治县", "30" });
            citys.Add(new List<string>() { "391", "重庆市", "30" });
            citys.Add(new List<string>() { "398", "铜梁县", "30" });
            citys.Add(new List<string>() { "255", "武隆县", "30" });
            citys.Add(new List<string>() { "248", "梁平县", "30" });
            citys.Add(new List<string>() { "202", "忠县", "30" });
            citys.Add(new List<string>() { "65", "云阳县", "30" });
            citys.Add(new List<string>() { "135", "垫江县", "30" });
            citys.Add(new List<string>() { "136", "城口县", "30" });
            citys.Add(new List<string>() { "143", "大足县", "30" });
            citys.Add(new List<string>() { "149", "奉节县", "30" });
            citys.Add(new List<string>() { "175", "巫山县", "30" });
            citys.Add(new List<string>() { "176", "巫溪县", "30" });
            citys.Add(new List<string>() { "191", "开县", "30" });
            citys.Add(new List<string>() { "196", "彭水苗族土家族自治县", "30" });
            citys.Add(new List<string>() { "906", "南岸区", "30" });
            citys.Add(new List<string>() { "121", "咸阳市", "31" });
            citys.Add(new List<string>() { "363", "西安市", "31" });
            citys.Add(new List<string>() { "287", "渭南市", "31" });
            citys.Add(new List<string>() { "258", "汉中市", "31" });
            citys.Add(new List<string>() { "252", "榆林市", "31" });
            citys.Add(new List<string>() { "189", "延安市", "31" });
            citys.Add(new List<string>() { "165", "宝鸡市", "31" });
            citys.Add(new List<string>() { "156", "安康市", "31" });
            citys.Add(new List<string>() { "126", "商洛市", "31" });
            citys.Add(new List<string>() { "397", "铜川市", "31" });
            citys.Add(new List<string>() { "242", "果洛州", "32" });
            citys.Add(new List<string>() { "275", "海东地区", "32" });
            citys.Add(new List<string>() { "276", "海北州", "32" });
            citys.Add(new List<string>() { "277", "海南州", "32" });
            citys.Add(new List<string>() { "279", "海西州", "32" });
            citys.Add(new List<string>() { "307", "玉树州", "32" });
            citys.Add(new List<string>() { "362", "西宁市", "32" });
            citys.Add(new List<string>() { "435", "黄南州", "32" });
            citys.Add(new List<string>() { "425", "香港", "33" });
            citys.Add(new List<string>() { "3116", "香港南区", "33" });
            citys.Add(new List<string>() { "3115", "香港北区", "33" });
            citys.Add(new List<string>() { "3114", "香港东区", "33" });
            citys.Add(new List<string>() { "2737", "观塘区", "33" });
            citys.Add(new List<string>() { "2733", "西贡区", "33" });
            citys.Add(new List<string>() { "2657", "葵青区", "33" });
            citys.Add(new List<string>() { "2626", "荃湾区", "33" });
            citys.Add(new List<string>() { "2465", "离岛区", "33" });
            citys.Add(new List<string>() { "2248", "湾仔区", "33" });
            citys.Add(new List<string>() { "2202", "深水埗区", "33" });
            citys.Add(new List<string>() { "2086", "油尖旺区", "33" });
            citys.Add(new List<string>() { "2068", "沙田区", "33" });
            citys.Add(new List<string>() { "1388", "屯门区", "33" });
            citys.Add(new List<string>() { "1159", "大埔区", "33" });
            citys.Add(new List<string>() { "758", "元朗区", "33" });
            citys.Add(new List<string>() { "650", "九龙城区", "33" });
            citys.Add(new List<string>() { "565", "中西区", "33" });
            citys.Add(new List<string>() { "3177", "黄大仙区", "33" });
            citys.Add(new List<string>() { "36", "七台河市", "34" });
            citys.Add(new List<string>() { "438", "黑河市", "34" });
            citys.Add(new List<string>() { "432", "鹤岗市", "34" });
            citys.Add(new List<string>() { "430", "鸡西市", "34" });
            citys.Add(new List<string>() { "335", "绥化市", "34" });
            citys.Add(new List<string>() { "305", "牡丹江市", "34" });
            citys.Add(new List<string>() { "141", "大庆市", "34" });
            citys.Add(new List<string>() { "139", "大兴安岭地区", "34" });
            citys.Add(new List<string>() { "123", "哈尔滨市", "34" });
            citys.Add(new List<string>() { "101", "双鸭山市", "34" });
            citys.Add(new List<string>() { "73", "佳木斯市", "34" });
            citys.Add(new List<string>() { "70", "伊春市", "34" });
            citys.Add(new List<string>() { "442", "齐齐哈尔市", "34" });
            return citys;
        }
        public List<list_item> provinces()
        {
            List<list_item> data_source = new List<list_item>();
            data_source.Add(new list_item() { Id = "1", Name = "上海" });
            data_source.Add(new list_item() { Id = "2", Name = "云南" });
            data_source.Add(new list_item() { Id = "3", Name = "内蒙古" });
            data_source.Add(new list_item() { Id = "4", Name = "北京" });
            data_source.Add(new list_item() { Id = "5", Name = "台湾" });
            data_source.Add(new list_item() { Id = "6", Name = "吉林" });
            data_source.Add(new list_item() { Id = "7", Name = "四川" });
            data_source.Add(new list_item() { Id = "8", Name = "天津" });
            data_source.Add(new list_item() { Id = "9", Name = "宁夏" });
            data_source.Add(new list_item() { Id = "10", Name = "安徽" });
            data_source.Add(new list_item() { Id = "11", Name = "山东" });
            data_source.Add(new list_item() { Id = "12", Name = "山西" });
            data_source.Add(new list_item() { Id = "13", Name = "广东" });
            data_source.Add(new list_item() { Id = "14", Name = "广西" });
            data_source.Add(new list_item() { Id = "15", Name = "新疆" });
            data_source.Add(new list_item() { Id = "16", Name = "江苏" });
            data_source.Add(new list_item() { Id = "17", Name = "江西" });
            data_source.Add(new list_item() { Id = "18", Name = "河北" });
            data_source.Add(new list_item() { Id = "19", Name = "河南" });
            data_source.Add(new list_item() { Id = "20", Name = "浙江" });
            data_source.Add(new list_item() { Id = "21", Name = "海南" });
            data_source.Add(new list_item() { Id = "22", Name = "湖北" });
            data_source.Add(new list_item() { Id = "23", Name = "湖南" });
            data_source.Add(new list_item() { Id = "24", Name = "澳门" });
            data_source.Add(new list_item() { Id = "25", Name = "甘肃" });
            data_source.Add(new list_item() { Id = "26", Name = "福建" });
            data_source.Add(new list_item() { Id = "27", Name = "西藏" });
            data_source.Add(new list_item() { Id = "28", Name = "贵州" });
            data_source.Add(new list_item() { Id = "29", Name = "辽宁" });
            data_source.Add(new list_item() { Id = "30", Name = "重庆" });
            data_source.Add(new list_item() { Id = "31", Name = "陕西" });
            data_source.Add(new list_item() { Id = "32", Name = "青海" });
            data_source.Add(new list_item() { Id = "33", Name = "香港" });
            data_source.Add(new list_item() { Id = "34", Name = "黑龙江" });
            return data_source;
        }
    }
}
